# Generated by Django 4.2.7 on 2024-01-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.productversion', verbose_name='версия'),
        ),
    ]
